### ISSUE TITLE
Bug in tB v417?

### ISSUE THREAD

**Issue by GCuser99** [Theadd/ArrayList#5]
Not sure this is an error in ArrayList or something else, but as of v417, I cannot compile my project:

```compilation (codegen) error detected in 'Enumerator.Class_Terminate' at line #142```

**Comment by GCuser99** [comment]
Problem persists in v418 & v419... but I can compile in v416.

**Comment by GCuser99** [comment]
I think I found the problem and [reported the issue](https://github.com/twinbasic/twinbasic/issues/1710). Looks like you just have to turn off experimental Project Property "Constant Function Folding" set to "No" and recompile it...

**Comment by GCuser99** [comment]
Fixed in v420!

**Comment by Theadd** [comment]
Hi @GCuser99 

> Fixed in v420!

Many thanks for involving and getting it fixed by yourself!! That's very helpful =)
